[package]
org = "isuruuy"
name = "NzPatient"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org="healthcare"
name="nzbasegen"
version="1.0.0"
repository="local"
