[package]
org = "healthcare"
name = "nzbase.practitionerrole"
version = "2.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "PractitionerRole", "r4", "nzbase"]
template = true
